version: "3.8"

services:
  frontend:
    extends:
      file: common.yaml
      service: frontend
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      BACKEND_URL: https://admin.i2tec.ec
      BACKEND_IMAGES: https://admin.i2tec.ec
    ports:
      - "3000:4321"
