version: "3.8"

services:
  frontend:
    extends:
      file: common.yaml
      service: frontend
    build: .
    command: bun run dev --host
    ports:
      - "4321:4321"
    volumes:
      - ./public:/app/public
      - ./src:/app/src
