version: "3.8"

services:
  frontend:
    extends:
      file: common.yaml
      service: frontend
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:4321"
    environment:
      BACKEND_URL: https://admin.i2tec.ec
      BACKEND_IMAGES: https://admin.i2tec.ec

networks:
  default:
    name: nginx_default
    external: true