version: "3"

services:
  frontend:
    container_name: frontend
    image: ghcr.io/jhonromero26/i2tec-frontend:latest
    restart: unless-stopped
    ports:
      - "3000:4321"
    volumes:
      - ./public:/app/public
    networks:
      - i2tec
      - nginx_default

networks:
  i2tec:
    name: i2tec
    driver: bridge
    driver_opts:
      encrypted: 1

  nginx_default:
    name: nginx_default
    driver: bridge
