version: "3.8"

services:
  frontend:
    extends:
      file: common.yaml
      service: frontend
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      BACKEND_URL: http://backend:1337
      BACKEND_IMAGES: https://admin.i2tec.ec
    ports:
      - "3000:4321"
    networks:
      - i2tec-backend

networks:
  i2tec-backend:
    name: i2tec-backend
    external: true
