version: "3.8"

services:
  frontend:
    container_name: frontend
    image: ghcr.io/jhonromero26/i2tec-frontend:latest
    restart: unless-stopped
    build: .
    environment:
      BACKEND_URL: https://admin.i2tec.ec
      BACKEND_IMAGES: https://admin.i2tec.ec

networks:
  default:
    name: nginx_default
    external: true
